### ISSUE TITLE
对动态点云进行地面分割，会出现地面点闪烁问题

### ISSUE THREAD

**Issue by HXB-1997** [NVIDIA-AI-IOT/cuPCL#37]
我修改了cuPCL的segment代码，加入了ROS接口，订阅动态播放点云包，进行地面分割，有时可以很好的去除地面点，有时地面点无法去除。我的雷达平台相对地面静止，但是地面点云会以一定频率闪烁。想知道哪里出问题了

**Comment by MagicalBrain** [comment]
你确定你的雷达每次传回来的点云数据都是完整的吗？看看每次传回来的点云数量有没有明显变化，说不定是点云数据还没传输完整你就开始分割了，自然就会出现地面去不掉，然后就是地面点闪烁的情况。

**Comment by ZFcvYes** [comment]
我也出现了该现象，使用的是同一帧点云，请问您解决了吗？也使用了cudaStreamSynchronize(stream_);

**Comment by HXB-1997** [comment]
项目烂尾了，后续没有继续跟进
